// <auto-generated />
using System;
using HistorySampleWebApp.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HistorySampleWebApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("13970930203735_Add-teacher-Entity")]
    partial class AddteacherEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HistorySampleWebApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CrearedDateTime");

                    b.Property<DateTime>("DeletedDatTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastAccesDevice");

                    b.Property<string>("LastAccessIp");

                    b.Property<DateTime>("LastEditedDateTime");

                    b.Property<string>("Name");

                    b.Property<int>("age");

                    b.HasKey("Id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("HistorySampleWebApp.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
